site_name: label.dev
repo_url: https://github.com/textualize/label.dev
# custom_dir: overrides
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  palette:
    scheme: slate
plugins:
  - social
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
docs_dir: docs
nav:
  - Labels:
      - "index.md"
      - "bug.md"
      - "documentation.md"
      - "duplicate.md"
      - "enhancement.md"
      - "good-first-issue.md"
      - "help-wanted.md"
      - "question.md"
      - "wontfix.md"
  - Articles:
      - "./articles/closed-issue.md"
      - "./articles/minimal-reproducible-example.md"
      - "./articles/xy-problem.md"
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@textualize
